import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#c3c6d4',
        'tertiary-fixed-dim': '#ebb2ff',
        'on-tertiary': '#520072',
        'electric-cyan': '#00F2FF',
        'inverse-primary': '#5a5e6a',
        'primary-container': '#0b0f19',
        error: '#ffb4ab',
        'surface-tint': '#c3c6d4',
        'on-primary': '#2c303b',
        'on-tertiary-container': '#c02aff',
        secondary: '#ddfcff',
        'on-background': '#d6e3f8',
        'inverse-surface': '#d6e3f8',
        'surface-glass': 'rgba(11, 15, 25, 0.6)',
        'on-primary-container': '#787b88',
        'border-glow': 'rgba(0, 242, 255, 0.2)',
        'surface-bright': '#2e3a4a',
        'on-tertiary-fixed-variant': '#74009f',
        'tertiary-container': '#1f002e',
        'on-error': '#690005',
        tertiary: '#ebb2ff',
        'on-secondary': '#00363a',
        'on-surface-variant': '#c6c6cc',
        'primary-fixed': '#dfe2f1',
        'surface-container-highest': '#293645',
        'surface-container-lowest': '#030f1d',
        'deep-obsidian': '#0B0F19',
        surface: '#071423',
        'surface-variant': '#293645',
        'on-secondary-container': '#006a70',
        'secondary-fixed': '#74f5ff',
        outline: '#909096',
        'on-surface': '#d6e3f8',
        'error-red': '#FF4D4D',
        'on-secondary-fixed-variant': '#004f54',
        'surface-dim': '#071423',
        'primary-fixed-dim': '#c3c6d4',
        'secondary-fixed-dim': '#00dbe7',
        'secondary-container': '#00f1fe',
        'on-primary-fixed': '#171b26',
        'surface-container-high': '#1e2b3a',
        'error-container': '#93000a',
        background: '#071423',
        'inverse-on-surface': '#253141',
        'on-primary-fixed-variant': '#434652',
        'on-secondary-fixed': '#002022',
        'surface-container-low': '#0f1c2b',
        'on-tertiary-fixed': '#320047',
        'tertiary-fixed': '#f8d8ff',
        'surface-container': '#14202f',
        'cyber-purple': '#BC13FE',
        'on-error-container': '#ffdad6',
        'outline-variant': '#46464c',
      },
      fontFamily: {
        'headline-md': ['Space Grotesk'],
        'body-md': ['Inter'],
        'display-lg': ['Space Grotesk'],
        'label-caps': ['Space Grotesk'],
        'display-lg-mobile': ['Space Grotesk'],
        'label-mono': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'headline-lg': ['Space Grotesk'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        unit: '8px',
        'margin-mobile': '20px',
        'container-max': '1440px',
        'bento-gap': '24px',
        gutter: '24px',
      },
      animation: {
        'pulse-cyan': 'pulse-cyan 3s infinite ease-in-out',
        'reveal': 'reveal 1.2s forwards cubic-bezier(0.77, 0, 0.175, 1)',
        'glow': 'glow 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        'pulse-cyan': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.6', transform: 'scale(1.05)' },
        },
        reveal: {
          to: { clipPath: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(0, 242, 255, 0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(0, 242, 255, 0.4)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
